export { default as AboutPage } from './AboutPage'
export { default as DetailPage } from './DetailPage'
export { default as ErrorPage } from './ErrorPage'
export { default as ImprintPage } from './ImprintPage'
export { default as LoadingPage } from './LoadingPage'
export { default as ProjectsPage } from './ProjectsPage'
export { default as WelcomePage } from './WelcomePage'
export { default as PhonePairPage } from './PhonePairPage'
